version: "3.8"

x-env: &env
  CELERY_BROKER: redis://redis:6379/0
  CELERY_BACKEND: redis://redis:6379/0
  PYTHONPATH: /usr/src/app:/usr/src/app/py-substrate-interface/:/usr/src/app/py-scale-codec/
  ENVIRONMENT: dev
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_NAME: "${DB_DATABASE}"
  SUBSTRATE_RPC_URL: "${SUBSTRATE_RPC_URL}"
  TYPE_REGISTRY: core
  TYPE_REGISTRY_FILE: app/type_registry/custom_types.json
  SUBSTRATE_ADDRESS_TYPE: 42
  SUBSTRATE_METADATA_VERSION: 12
  SUBSTRATE_STORAGE_BALANCE: Account
  SUBSTRATE_STORAGE_INDICES: Accounts
  FINALIZATION_ONLY: 1
  SIDECAR_API_URL: "${SIDECAR_API_URL}"
  BLOCK_HISTORY_PERIOD: "${BLOCK_HISTORY_PERIOD}"
  LOG_LEVEL: INFO
  DEBUG:

services:
  explorer-api:
    build: explorer-api/.
    image: polkascan/pre-explorer-api:latest
    hostname: explorer-api
    volumes:
      - "./explorer-api:/usr/src/app"
    command: ./start.sh
    environment:
      <<: *env
      PYTHONPATH: /usr/src/app
      EVM_RPC_URL: "${EVM_RPC_URL}"
      EVM_DEP_ADDRESS: "{EVM_DEP_ADDRESS}"

    depends_on:
      - harvester-api

  harvester-api:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    hostname: harvester-api
    volumes:
      - "./harvester:/usr/src/app"
    command: ./start.sh
    environment:
      <<: *env
    depends_on:
      - redis
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 6

  harvester-worker:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - "./harvester:/usr/src/app"
    command: sh -c 'celery -A app.tasks worker --loglevel=$${LOG_LEVEL}'
    environment:
      <<: *env
      LOG_LEVEL: INFO
    depends_on:
      - redis
      - mysql
      - harvester-api

  harvester-beat:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - "./harvester:/usr/src/app"
      - "/usr/src/app/data"
    command: celery -A app.tasks beat --loglevel=INFO  --schedule="data/celerybeat-schedule" --pidfile="data/celerybeat.pid"
    environment:
      <<: *env
    depends_on:
      - redis
      - mysql

  harvester-monitor:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    ports:
      - "5555:5555"
    command: flower -A app.tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:3.2.11
    hostname: redis

  mysql:
    image: mysql:8.2.0
    hostname: mysql
    cap_add:
      - SYS_NICE
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}

  explorer-gui:
    image: polkascan/pre-explorer-gui:latest
    build:
      context: explorer-gui/.
      args:
        - API_URL=http://localhost:8080/api/v1
        - NGINX_CONF=nginx/polkascan-prod.conf
        - NETWORK_NAME=Deeper
        - NETWORK_ID=deeper
        - NETWORK_TYPE=pre
        - CHAIN_TYPE=relay
        - NETWORK_TOKEN_SYMBOL=DPR
        - NETWORK_TOKEN_DECIMALS=18
        - NETWORK_COLOR_CODE=21C355
        - ENV_CONFIG=docker
    ports:
      - "8080:80"
    depends_on:
      - harvester-api
      - explorer-api

  # api-sidecar:
  #   image: parity/substrate-api-sidecar:v11.3.15
  #   volumes:
  #     - "./harvester/app/type_registry/custom_types.json:/tmp/custom_types.json"
  #   environment:
  #     - SAS_SUBSTRATE_WS_URL=ws://172.17.0.1:9955
  #     - SAS_SUBSTRATE_TYPES=/tmp/custom_types.json

volumes:
  db-data:
