"""block_missing_table

Revision ID: a7c27be741fb
Revises: b17212572fca
Create Date: 2022-01-12 06:48:57.256145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7c27be741fb'
down_revision = 'b17212572fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_block_missing',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('start', sa.Integer(), nullable=False),
        sa.Column('end', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_block_missing_end'), 'data_block_missing', ['end'], unique=False)
    op.create_index(op.f('ix_data_block_missing_start'), 'data_block_missing', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_block_missing_start'), table_name='data_block_missing')
    op.drop_index(op.f('ix_data_block_missing_end'), table_name='data_block_missing')
    op.drop_table('data_block_missing')
    # ### end Alembic commands ###
